apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo-app
  template:
    metadata:
      labels:
        app: react-todo-app
    spec:
      containers:
        - name: react-todo-app
          image: your-dockerhub-username/react-todo-app:latest # IMPORTANT: Replace with your Docker Hub image
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: postgres-service
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: react-todo-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
