version: '3.8'
services:
  app:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
